spring.application.name=controlgasto
server.address=0.0.0.0

# Configuración de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/controlgasto?useSSL=false&serverTimezone=America/Lima
spring.datasource.username=root
spring.datasource.password=server8@MySQL

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=uploads

# CORS - orígenes permitidos (separados por coma)
cors.allowed-origins=http://localhost:4200